### ISSUE TITLE
ImportError: Q-testing/tensorflow.python._pywrap_tensorflow_internal.x86_64-linux-gnu.so: invalid ELF header

### ISSUE THREAD

**Issue by Jasonwangsonghe** [anlalalu/Q-testing#1]
在运行./Q-testing/main -r CONF.txt时出现的错误，使用file命令查看该so文件类型时，输出ASCII txt

**Comment by xixiAndpipi** [comment]
Fixed. The newest version of Q-testing is now available in oneDrive.
