### ISSUE TITLE
failure `GLIBCXX_3.4.22' not found when try to run in ubuntu 18

### ISSUE THREAD

**Issue by licollins** [anlalalu/Q-testing#7]
Hello,

I am trying to run Q-testing in my ubuntu 18, I have the requirements (python, uiautomatior, android) in correct versions but I got the error: Version `GLIBCXX_3.4.22' not found (adb require)
I attached the error, I need to run an experiment,  can you please help me?
![failure](https://user-images.githubusercontent.com/14595529/103768320-a691f880-4ff8-11eb-82aa-38aab1d0d583.png)

**Comment by RichardHoOoOo** [comment]
Hi @licollins , I encountered a similar issue (#3 ) before. This means your OS does not support GLIBCXX_3.4.22. We fix this issue by upgrading our OS.

**Comment by licollins** [comment]
Thanks, this error was fixed
